export const categorias = [
    "Electrónica",
    "Hogar",
    "Ropa",
    "Automotriz",
    "Muebles",
    "Juguetes",
    "Deportes",
    "Herramientas",
    "Jardinería",
    "Mascotas",
    "Salud y Belleza",
    "Alimentos y Bebidas",
    "Arte y Manualidades",
    "Libros y Revistas",
    "Música e Instrumentos",
    "Videojuegos",
    "Antigüedades",
    "Coleccionables",
    "Bebés y Niños",
    "Cámaras y Fotografía",
    "Computación",
    "Celulares y Accesorios",
    "Industria y Oficina",
    "Viajes y Turismo",
    "Servicios"
  ];